# Delete Commit History
# Only keep the active/current commit

name: delete-commit-history

on:
  workflow_dispatch:  # Manual triggering
  #schedule:
  #  - cron: "0 1 * * *" 


jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        repository: ProjectPythia/api-cookbook
        fetch-depth: 0 # Fetch whole history
        path: gh-pages

    - name: Get last commit messages
      run: |
        git log -1 --pretty=%B
