# Delete Commit History
# Only keep the active/current commit

name: delete-commit-history

on:
  workflow_dispatch:  # Manual triggering
  schedule:
    - cron: "0 1 * * *" 


jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Switch to gh-pages branch
    - uses: actions/checkout@v5
      with:
        path: gh-pages

    - name: Get last commit messages
      run: |
        git log -1 --pretty=%B
