# Delete Deployment History
# Only keep the active/current deployment

name: delete-deployment-history

on:
  page_build: # When a push is made to a GitHub Pages-enabled branch
  workflow_dispatch:  # Manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Delete deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
