# Delete Commit History
# Only keep the active/current commit

name: delete-commit-history

on:
  workflow_dispatch:  # Manual triggering
  #schedule:
  #  - cron: "0 1 * * *" 

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        ref: gh-pages # change branch
        fetch-depth: 0 # Fetch entire history
    - name: Git Log
      run: |
        echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        echo "${{ COMMIT_MSG }}"
